// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEuz4OsasXB2Jm8LILtS9NSpObhq-vE1s',
    appId: '1:634829160318:web:31e4128ab6183dc7893d2f',
    messagingSenderId: '634829160318',
    projectId: 'h4bit-9b8ae',
    authDomain: 'h4bit-9b8ae.firebaseapp.com',
    storageBucket: 'h4bit-9b8ae.appspot.com',
    measurementId: 'G-H6YM4Y0NCJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUxQjs0T-Ei4Xqcs9Jlz2ITgckLOck_po',
    appId: '1:634829160318:android:8f311ddf4d61ea33893d2f',
    messagingSenderId: '634829160318',
    projectId: 'h4bit-9b8ae',
    storageBucket: 'h4bit-9b8ae.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpMlFi3-NrRCZrg74qAP5VZefaNWwfEX8',
    appId: '1:634829160318:ios:5d26f76cf41f9b87893d2f',
    messagingSenderId: '634829160318',
    projectId: 'h4bit-9b8ae',
    storageBucket: 'h4bit-9b8ae.appspot.com',
    iosBundleId: 'com.example.h4bit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpMlFi3-NrRCZrg74qAP5VZefaNWwfEX8',
    appId: '1:634829160318:ios:5d26f76cf41f9b87893d2f',
    messagingSenderId: '634829160318',
    projectId: 'h4bit-9b8ae',
    storageBucket: 'h4bit-9b8ae.appspot.com',
    iosBundleId: 'com.example.h4bit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBEuz4OsasXB2Jm8LILtS9NSpObhq-vE1s',
    appId: '1:634829160318:web:d795400e765a2ad2893d2f',
    messagingSenderId: '634829160318',
    projectId: 'h4bit-9b8ae',
    authDomain: 'h4bit-9b8ae.firebaseapp.com',
    storageBucket: 'h4bit-9b8ae.appspot.com',
    measurementId: 'G-TZ4PTKFHQT',
  );
}
